"""init

Revision ID: f4069b602566
Revises:
Create Date: 2026-03-02 08:00:06.645218

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f4069b602566"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
